name = "PolytopeMeshes"
uuid = "a084ef37-6317-401f-8925-353d213336fa"
version = "0.1.0"
authors = ["Øystein Klemetsdal"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"

[extensions]
PolytopeMeshesGLMakieExt = "GLMakie"
PolytopeMeshesGmshExt = "Gmsh"

[compat]
GLMakie = "0.9, 0.10, 0.11, 0.12, 0.13"
Gmsh = "0.3, 0.4"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
